---
title: "Terry Haohui Fang Site"
date: 2021-09-06
---

# biostat776-intro-Terry-Haohui-Fang
## Terry's site
Hello everyone, this is the 1st time I experience 'coding'. I would love to make friends with you all. 
Find me at
**snapchat-Terry Haohui Fang**
**Wechat-huigethearrow**


## Fun facts
1. I am expert in cooking red braised pork (a Chinese Cuisine) and I love eating what I cook. It's realy really good!
2. Before this session, I barely have coding experience. So I am a lame coder (don't know whether I will still be). Don't hesitate to give me a hand and I can teach you biogeek skills. 
3. I am a home boy mostly~ but love to travel if there is company.

## Academic background
I did my undergraduate degree in Biological Sciences. So cells and some experimental gadgets were my toys LOL. Hopefully I can add programming to my toy list after this course.

That being said, I have 0 experience in almost any kinds of programming languages. What I used todo is using UI softwares. Really willing to learn from you!

## Interesting websites
1. [Biomedical news media-BioWorld](https://www.bioworld.com/) 
2. [Read scientific articles with peers and comments thereof-Pubpeers](https://pubpeer.com/static/about)
